# APPLICATION
# ===================================
spring.application.name=pati-api


# ===================================
# DATABASE
# ===================================
# Local PostgreSQL (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/pati_db
spring.datasource.username=postgres
spring.datasource.password=Toto1982!!!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true